/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pqt;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class CalculoVelocidades extends javax.swing.JDialog {

    /**
     * Creates new form CalculoVelocidades
     * @param parent
     * @param modal
     */
    public CalculoVelocidades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Cálculo de velocidades");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        txt_Dmax = new javax.swing.JTextField();
        txt_Dmin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lbl_ImagenRPM = new javax.swing.JLabel();
        lbl_ImagenRPM1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_Vmin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Vmax = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_RPM = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_RPM1 = new javax.swing.JTable();
        btn_CalcularRPM = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txt_RPMd = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Vc = new javax.swing.JTable();
        btn_CalcularVc = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txt_RPMcalc2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_DiamCalc2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_Vccalc = new javax.swing.JTextField();
        btn_CalcularVcCalc1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txt_Vc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_DiamCalc1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_RPMcalc = new javax.swing.JTextField();
        btn_CalcularRPMcalc = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel13.setText("Diametro max. [mm]:");

        txt_Dmax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Dmax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_DmaxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_DmaxFocusLost(evt);
            }
        });
        txt_Dmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DmaxActionPerformed(evt);
            }
        });

        txt_Dmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Dmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_DminFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_DminFocusLost(evt);
            }
        });
        txt_Dmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DminActionPerformed(evt);
            }
        });

        jLabel8.setText("Diametro min. [mm:]");

        lbl_ImagenRPM.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ImagenRPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RPM.jpg"))); // NOI18N
        lbl_ImagenRPM.setOpaque(true);

        lbl_ImagenRPM1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ImagenRPM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vc.jpg"))); // NOI18N
        lbl_ImagenRPM1.setOpaque(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Vc(min)[m/min]:");

        txt_Vmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Vmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_VminFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_VminFocusLost(evt);
            }
        });
        txt_Vmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_VminActionPerformed(evt);
            }
        });

        jLabel4.setText("Vc(max)[m/min]:");

        txt_Vmax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Vmax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_VmaxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_VmaxFocusLost(evt);
            }
        });
        txt_Vmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_VmaxActionPerformed(evt);
            }
        });

        tbl_RPM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_RPM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "RPM (Vcmin, Dmin)", "RPM (Vcmin, Dmax)"
            }
        ));
        tbl_RPM.setEnabled(false);
        tbl_RPM.setPreferredSize(new java.awt.Dimension(150, 20));
        tbl_RPM.setRowHeight(20);
        jScrollPane2.setViewportView(tbl_RPM);

        tbl_RPM1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_RPM1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "RPM (Vcmax, Dmin)", "RPM (Vcmax, Dmax)"
            }
        ));
        tbl_RPM1.setEnabled(false);
        tbl_RPM1.setPreferredSize(new java.awt.Dimension(150, 20));
        tbl_RPM1.setRowHeight(20);
        jScrollPane4.setViewportView(tbl_RPM1);

        btn_CalcularRPM.setText("Calcular");
        btn_CalcularRPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularRPMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Vmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Vmax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btn_CalcularRPM))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txt_Vmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Vmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CalcularRPM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setText("RPM límite (G50):");

        txt_RPMd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_RPMd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_RPMdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_RPMdFocusLost(evt);
            }
        });
        txt_RPMd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RPMdActionPerformed(evt);
            }
        });

        tbl_Vc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_Vc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Vc (con Dmin) [m/min]", "Vc (con Dmax) [m/min]"
            }
        ));
        tbl_Vc.setEnabled(false);
        tbl_Vc.setPreferredSize(new java.awt.Dimension(150, 20));
        tbl_Vc.setRowHeight(20);
        jScrollPane3.setViewportView(tbl_Vc);

        btn_CalcularVc.setText("Calcular");
        btn_CalcularVc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularVcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_RPMd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btn_CalcularVc)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_RPMd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CalcularVc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setText("RPM:");

        txt_RPMcalc2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_RPMcalc2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_RPMcalc2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_RPMcalc2FocusLost(evt);
            }
        });
        txt_RPMcalc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RPMcalc2ActionPerformed(evt);
            }
        });

        jLabel19.setText("Diametro [mm]:");

        txt_DiamCalc2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_DiamCalc2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_DiamCalc2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_DiamCalc2FocusLost(evt);
            }
        });
        txt_DiamCalc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DiamCalc2ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Vc [m/min]:");

        txt_Vccalc.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        txt_Vccalc.setForeground(new java.awt.Color(0, 0, 255));
        txt_Vccalc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Vccalc.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txt_Vccalc.setEnabled(false);
        txt_Vccalc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_VccalcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_VccalcFocusLost(evt);
            }
        });
        txt_Vccalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_VccalcActionPerformed(evt);
            }
        });

        btn_CalcularVcCalc1.setText("Calcular");
        btn_CalcularVcCalc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularVcCalc1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_RPMcalc2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Vccalc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_DiamCalc2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_CalcularVcCalc1)
                .addGap(119, 119, 119))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_RPMcalc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txt_DiamCalc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Vccalc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CalcularVcCalc1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setText("Vc [m/min]:");

        txt_Vc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Vc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_VcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_VcFocusLost(evt);
            }
        });
        txt_Vc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_VcActionPerformed(evt);
            }
        });

        jLabel16.setText("Diametro [mm]:");

        txt_DiamCalc1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_DiamCalc1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_DiamCalc1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_DiamCalc1FocusLost(evt);
            }
        });
        txt_DiamCalc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DiamCalc1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("RPM:");

        txt_RPMcalc.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        txt_RPMcalc.setForeground(new java.awt.Color(0, 0, 255));
        txt_RPMcalc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_RPMcalc.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txt_RPMcalc.setEnabled(false);
        txt_RPMcalc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_RPMcalcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_RPMcalcFocusLost(evt);
            }
        });
        txt_RPMcalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RPMcalcActionPerformed(evt);
            }
        });

        btn_CalcularRPMcalc.setText("Calcular");
        btn_CalcularRPMcalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularRPMcalcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Vc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_DiamCalc1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_RPMcalc, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(btn_CalcularRPMcalc)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_Vc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txt_DiamCalc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_RPMcalc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CalcularRPMcalc)
                .addGap(15, 15, 15))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Dmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Dmax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ImagenRPM1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ImagenRPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13)
                            .addComponent(txt_Dmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Dmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_ImagenRPM1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_ImagenRPM, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_VminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_VminFocusGained
        txt_Vmin.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_VminFocusGained

    private void txt_VminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_VminFocusLost
        txt_Vmin.setBackground(Color.white);
    }//GEN-LAST:event_txt_VminFocusLost

    private void txt_VminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_VminActionPerformed
        txt_Vmin.transferFocus();
    }//GEN-LAST:event_txt_VminActionPerformed

    private void txt_DmaxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DmaxFocusGained
        txt_Dmax.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_DmaxFocusGained

    private void txt_DmaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DmaxFocusLost
        txt_Dmax.setBackground(Color.white);
    }//GEN-LAST:event_txt_DmaxFocusLost

    private void txt_DmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DmaxActionPerformed
        txt_Dmax.transferFocus();
    }//GEN-LAST:event_txt_DmaxActionPerformed

    private void txt_RPMdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RPMdFocusGained
        txt_RPMd.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_RPMdFocusGained

    private void txt_RPMdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RPMdFocusLost
        txt_RPMd.setBackground(Color.white);
    }//GEN-LAST:event_txt_RPMdFocusLost

    private void txt_RPMdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RPMdActionPerformed
        txt_RPMd.transferFocus();
    }//GEN-LAST:event_txt_RPMdActionPerformed

    private void txt_DminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DminFocusGained
        txt_Dmin.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_DminFocusGained

    private void txt_DminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DminFocusLost
        txt_Dmin.setBackground(Color.white);
    }//GEN-LAST:event_txt_DminFocusLost

    private void txt_DminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DminActionPerformed
        txt_Dmin.transferFocus();
    }//GEN-LAST:event_txt_DminActionPerformed

    private void btn_CalcularRPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularRPMActionPerformed
        if (!txt_Dmax.getText().equals("") && !txt_Dmin.getText().equals("") && !txt_Vmax.getText().equals("") && !txt_Vmin.getText().equals("")) {
            int RPM;
            RPM = (int) ((1000.0 * Double.parseDouble(txt_Vmin.getText())) / (Math.PI * Double.parseDouble(txt_Dmin.getText())));
            tbl_RPM.setValueAt(RPM, 0, 0);
            RPM = (int) ((1000.0 * Double.parseDouble(txt_Vmin.getText())) / (Math.PI * Double.parseDouble(txt_Dmax.getText())));
            tbl_RPM.setValueAt(RPM, 0, 1);
            RPM = (int) ((1000.0 * Double.parseDouble(txt_Vmax.getText())) / (Math.PI * Double.parseDouble(txt_Dmin.getText())));
            tbl_RPM1.setValueAt(RPM, 0, 0);
            RPM = (int) ((1000.0 * Double.parseDouble(txt_Vmax.getText())) / (Math.PI * Double.parseDouble(txt_Dmax.getText())));
            tbl_RPM1.setValueAt(RPM, 0, 1);            
        } else {
            JOptionPane.showConfirmDialog(this, "Para el cálculo necesita Dmax, Dmin, Vcmax, y Vcmin", "Faltan datos", JOptionPane.CLOSED_OPTION);
        }
    }//GEN-LAST:event_btn_CalcularRPMActionPerformed

    private void txt_VmaxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_VmaxFocusGained
        txt_Vmax.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_VmaxFocusGained

    private void txt_VmaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_VmaxFocusLost
        txt_Vmax.setBackground(Color.white);
    }//GEN-LAST:event_txt_VmaxFocusLost

    private void txt_VmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_VmaxActionPerformed
        txt_Vmax.transferFocus();
    }//GEN-LAST:event_txt_VmaxActionPerformed

    private void btn_CalcularVcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularVcActionPerformed
        if (!txt_RPMd.getText().equals("") && !txt_Dmin.getText().equals("") && !txt_Dmax.getText().equals("")) {
            int Vc;
            Vc = (int) ((Double.parseDouble(txt_RPMd.getText()) * Math.PI * Double.parseDouble(txt_Dmin.getText())) / 1000.0);
            tbl_Vc.setValueAt(Vc, 0, 0);
            Vc = (int) ((Double.parseDouble(txt_RPMd.getText()) * Math.PI * Double.parseDouble(txt_Dmax.getText())) / 1000.0);
            tbl_Vc.setValueAt(Vc, 0, 1);
        } else {
            JOptionPane.showConfirmDialog(this, "Para el cálculo necesita Dmax, Dmin, y RPM deseada", "Faltan datos", JOptionPane.CLOSED_OPTION);
        }
    }//GEN-LAST:event_btn_CalcularVcActionPerformed

    private void txt_VcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_VcFocusGained
        txt_Vc.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_VcFocusGained

    private void txt_VcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_VcFocusLost
        txt_Vc.setBackground(Color.white);
    }//GEN-LAST:event_txt_VcFocusLost

    private void txt_VcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_VcActionPerformed
        txt_Vc.transferFocus();        
    }//GEN-LAST:event_txt_VcActionPerformed

    private void btn_CalcularRPMcalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularRPMcalcActionPerformed
        int RPM;
        RPM = (int) ((1000.0 * Double.parseDouble(txt_Vc.getText())) / (Math.PI * Double.parseDouble(txt_DiamCalc1.getText())));
        txt_RPMcalc.setText(String.valueOf(RPM));
    }//GEN-LAST:event_btn_CalcularRPMcalcActionPerformed

    private void txt_DiamCalc1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DiamCalc1FocusGained
        txt_DiamCalc1.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_DiamCalc1FocusGained

    private void txt_DiamCalc1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DiamCalc1FocusLost
        txt_DiamCalc1.setBackground(Color.white);
    }//GEN-LAST:event_txt_DiamCalc1FocusLost

    private void txt_DiamCalc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DiamCalc1ActionPerformed
        txt_DiamCalc1.transferFocus();
    }//GEN-LAST:event_txt_DiamCalc1ActionPerformed

    private void txt_RPMcalcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RPMcalcFocusGained
        txt_RPMcalc.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_RPMcalcFocusGained

    private void txt_RPMcalcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RPMcalcFocusLost
        txt_RPMcalc.setBackground(Color.white);
    }//GEN-LAST:event_txt_RPMcalcFocusLost

    private void txt_RPMcalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RPMcalcActionPerformed
        txt_RPMcalc.transferFocus();
    }//GEN-LAST:event_txt_RPMcalcActionPerformed

    private void txt_RPMcalc2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RPMcalc2FocusGained
        txt_RPMcalc2.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_RPMcalc2FocusGained

    private void txt_RPMcalc2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RPMcalc2FocusLost
        txt_RPMcalc2.setBackground(Color.white);
    }//GEN-LAST:event_txt_RPMcalc2FocusLost

    private void txt_RPMcalc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RPMcalc2ActionPerformed
        txt_RPMcalc2.transferFocus();
    }//GEN-LAST:event_txt_RPMcalc2ActionPerformed

    private void txt_DiamCalc2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DiamCalc2FocusGained
        txt_DiamCalc2.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_DiamCalc2FocusGained

    private void txt_DiamCalc2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DiamCalc2FocusLost
        txt_DiamCalc2.setBackground(Color.white);
    }//GEN-LAST:event_txt_DiamCalc2FocusLost

    private void txt_DiamCalc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DiamCalc2ActionPerformed
        txt_DiamCalc2.transferFocus();
    }//GEN-LAST:event_txt_DiamCalc2ActionPerformed

    private void txt_VccalcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_VccalcFocusGained
        txt_Vccalc.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_VccalcFocusGained

    private void txt_VccalcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_VccalcFocusLost
        txt_Vccalc.setBackground(Color.white);
    }//GEN-LAST:event_txt_VccalcFocusLost

    private void txt_VccalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_VccalcActionPerformed
        txt_Vccalc.transferFocus();
    }//GEN-LAST:event_txt_VccalcActionPerformed

    private void btn_CalcularVcCalc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularVcCalc1ActionPerformed
            int Vc;
            Vc = (int) ((Double.parseDouble(txt_RPMcalc2.getText()) * Math.PI * Double.parseDouble(txt_DiamCalc2.getText())) / 1000.0);        
            txt_Vccalc.setText(String.valueOf(Vc));
    }//GEN-LAST:event_btn_CalcularVcCalc1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculoVelocidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculoVelocidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculoVelocidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculoVelocidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CalculoVelocidades dialog = new CalculoVelocidades(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CalcularRPM;
    private javax.swing.JButton btn_CalcularRPMcalc;
    private javax.swing.JButton btn_CalcularVc;
    private javax.swing.JButton btn_CalcularVcCalc1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_ImagenRPM;
    private javax.swing.JLabel lbl_ImagenRPM1;
    private javax.swing.JTable tbl_RPM;
    private javax.swing.JTable tbl_RPM1;
    private javax.swing.JTable tbl_Vc;
    private javax.swing.JTextField txt_DiamCalc1;
    private javax.swing.JTextField txt_DiamCalc2;
    private javax.swing.JTextField txt_Dmax;
    private javax.swing.JTextField txt_Dmin;
    private javax.swing.JTextField txt_RPMcalc;
    private javax.swing.JTextField txt_RPMcalc2;
    private javax.swing.JTextField txt_RPMd;
    private javax.swing.JTextField txt_Vc;
    private javax.swing.JTextField txt_Vccalc;
    private javax.swing.JTextField txt_Vmax;
    private javax.swing.JTextField txt_Vmin;
    // End of variables declaration//GEN-END:variables
}
