/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pqt;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Cilindrado extends javax.swing.JDialog {

    String Velocidad = "";
    String PosIni = "";
    String PosFin = "";
    String Perfil = "";
    String PosFinAc = "";
    String PosIniAc = "";
    int modoFinal = 0;

    /**
     * Creates new form Cil
     */
    public Cilindrado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        rdb_G50.setSelected(Principal.G50);
        rdb_G50.setEnabled(Principal.G50);
        rdb_G97.setSelected(!Principal.G50);
        txt_G96S.setEnabled(Principal.G50);
        ckb_Acabado.setSelected(false);
        ckb_Compenzacion.setSelected(false);
        if (Herramienta.IntExt) {
            this.setTitle("Cilindrado interior");
        } else {
            this.setTitle("Cilindrado exterior");
        }
        String ayuda = "* G0= movimiento rápido sin mecanizar" + '\n'
                + '\t' + "G0 Xx Zz" + '\n'
                + '\t' + '\t' + "x: posición final" + '\n'
                + '\t' + '\t' + "z: longitud final" + '\n' + '\n'
                + "* G1= interpolacion lineal:" + '\n'
                + '\t' + "G1 Xx Zz Ff" + '\n'
                + '\t' + '\t' + "x: diámetro final" + '\n'
                + '\t' + '\t' + "z: longitud final" + '\n'
                + '\t' + '\t' + "f: velocidad de avance" + '\n' + '\n'
                + "* G2= interpolacion circular en sentido horario:" + '\n'
                + '\t' + "G2 Xx Zz Rr Ff" + '\n'
                + '\t' + '\t' + "x: diámetro final" + '\n'
                + '\t' + '\t' + "z: posición final" + '\n'
                + '\t' + '\t' + "r: radio de la curva" + '\n'
                + '\t' + '\t' + "f: velocidad de avance" + '\n' + '\n'
                + "* G3= interpolacion circular en sentido antihorario:" + '\n'
                + '\t' + "G3 Xx Zz Rr Ff" + '\n'
                + '\t' + '\t' + "x: diámetro final" + '\n'
                + '\t' + '\t' + "z: posición final" + '\n'
                + '\t' + '\t' + "r: radio de la curva" + '\n'
                + '\t' + '\t' + "f: velocidad de avance" + '\n';
        txt_Ayuda.setText(ayuda);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel36 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_Ap = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_R = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_F = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_U = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_W = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Perfil = new javax.swing.JTextArea();
        btn_Aceptar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        txt_Des = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rdb_G50 = new javax.swing.JRadioButton();
        rdb_G97 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_G97S = new javax.swing.JTextField();
        txt_G96S = new javax.swing.JTextField();
        btn_Calcular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_G0iniX = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_G0iniZ = new javax.swing.JTextField();
        ckb_Refrigerante = new javax.swing.JCheckBox();
        ckb_Compenzacion = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Ayuda = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        ckb_Acabado = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        txt_AcS = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txt_AcF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txt_G0Xf = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txt_G0Zf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbx_PosFinal = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel36.setText("Descripcion:");

        jLabel20.setText("Profundidad de corte (ap):");

        txt_Ap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Ap.setToolTipText("Profundidad de corte por pasada");
        txt_Ap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_ApFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_ApFocusLost(evt);
            }
        });
        txt_Ap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApActionPerformed(evt);
            }
        });

        jLabel22.setText("[mm]");

        jLabel21.setText("Retraccion:");

        txt_R.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_R.setToolTipText("Valor de retraccion de la herramienta luego de la pasada");
        txt_R.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_RFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_RFocusLost(evt);
            }
        });
        txt_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RActionPerformed(evt);
            }
        });

        jLabel23.setText("[mm]");

        jLabel28.setText("F");

        txt_F.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_F.setToolTipText("Velocidad de avance");
        txt_F.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_FFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_FFocusLost(evt);
            }
        });
        txt_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FActionPerformed(evt);
            }
        });

        jLabel1.setText("[mm/rev]");

        jLabel26.setText("Sobremedida en X (U):");

        txt_U.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_U.setToolTipText("Sobrante de material en radio");
        txt_U.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_UFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_UFocusLost(evt);
            }
        });
        txt_U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UActionPerformed(evt);
            }
        });

        jLabel27.setText("Sobremedida en Z (W):");

        txt_W.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_W.setToolTipText("Sobrante de material en longitud");
        txt_W.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_WFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_WFocusLost(evt);
            }
        });
        txt_W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_WActionPerformed(evt);
            }
        });

        txt_Perfil.setColumns(20);
        txt_Perfil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Perfil.setRows(5);
        txt_Perfil.setToolTipText("Perfil deseado. El G0 en laprimera linea, y el G1 en la segunda no se colocan");
        txt_Perfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_PerfilKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txt_Perfil);

        btn_Aceptar.setText("Aceptar");
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        txt_Des.setToolTipText("Nombre descriptivo del proceso");
        txt_Des.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_DesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_DesFocusLost(evt);
            }
        });
        txt_Des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DesActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(rdb_G50);
        rdb_G50.setText("Velocidad de corte constante (G96):");
        rdb_G50.setToolTipText("Seleccione para velocidad de corte constante");
        rdb_G50.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdb_G50ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rdb_G97);
        rdb_G97.setSelected(true);
        rdb_G97.setText("Velocidad de cabezal constante (G97):");
        rdb_G97.setToolTipText("Seleccione para velocidad de husillo constante");
        rdb_G97.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdb_G97ItemStateChanged(evt);
            }
        });

        jLabel5.setText("Velocidad de corte:");

        jLabel6.setText("[m/min]");

        jLabel7.setText("[RPM]");

        jLabel9.setText("Velocidad:");

        txt_G97S.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G97S.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G97SFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G97SFocusLost(evt);
            }
        });
        txt_G97S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G97SActionPerformed(evt);
            }
        });

        txt_G96S.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G96S.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G96SFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G96SFocusLost(evt);
            }
        });
        txt_G96S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G96SActionPerformed(evt);
            }
        });

        btn_Calcular.setText("Calcular");
        btn_Calcular.setFocusable(false);
        btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdb_G50)
                    .addComponent(rdb_G97)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_G97S, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Calcular))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_G96S, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdb_G50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txt_G96S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdb_G97)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(txt_G97S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Calcular))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Posicionamiento inicial:");

        jLabel11.setText("X");

        txt_G0iniX.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G0iniX.setToolTipText("Posicion de seguridad en X");
        txt_G0iniX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G0iniXFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G0iniXFocusLost(evt);
            }
        });
        txt_G0iniX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G0iniXActionPerformed(evt);
            }
        });

        jLabel12.setText("Z");

        txt_G0iniZ.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G0iniZ.setToolTipText("Posicion de seguridad en Z");
        txt_G0iniZ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G0iniZFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G0iniZFocusLost(evt);
            }
        });
        txt_G0iniZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G0iniZActionPerformed(evt);
            }
        });

        ckb_Refrigerante.setText("Refrigerante On/Off");
        ckb_Refrigerante.setToolTipText("Seleccione para activar el refrigerante");

        ckb_Compenzacion.setSelected(true);
        ckb_Compenzacion.setText("Compensacion");
        ckb_Compenzacion.setToolTipText("Seleccione para realizar la compenzacion del radio de la herramienta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_G0iniX, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_G0iniZ, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ckb_Refrigerante)
                            .addComponent(ckb_Compenzacion))
                        .addGap(0, 7, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckb_Compenzacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_G0iniX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txt_G0iniZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckb_Refrigerante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setHorizontalScrollBar(null);

        txt_Ayuda.setColumns(20);
        txt_Ayuda.setRows(5);
        txt_Ayuda.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_Ayuda.setEnabled(false);
        jScrollPane2.setViewportView(txt_Ayuda);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ckb_Acabado.setSelected(true);
        ckb_Acabado.setText("Acabado");
        ckb_Acabado.setToolTipText("Seleccione si desea pasada de acabado");
        ckb_Acabado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_AcabadoItemStateChanged(evt);
            }
        });

        jLabel29.setText("Velocidad: S");

        txt_AcS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_AcS.setToolTipText("Velocidad en acabado");
        txt_AcS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_AcSFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_AcSFocusLost(evt);
            }
        });
        txt_AcS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AcSActionPerformed(evt);
            }
        });

        jLabel37.setText("F");

        txt_AcF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_AcF.setToolTipText("Avance en acabado");
        txt_AcF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_AcFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_AcFFocusLost(evt);
            }
        });
        txt_AcF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AcFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_AcS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_AcF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ckb_Acabado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ckb_Acabado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel37)
                        .addComponent(txt_AcF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(txt_AcS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel33.setText("Posicionamiento final:");

        jLabel34.setText("X");

        txt_G0Xf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G0Xf.setToolTipText("Posicion final en X");
        txt_G0Xf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G0XfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G0XfFocusLost(evt);
            }
        });
        txt_G0Xf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G0XfActionPerformed(evt);
            }
        });

        jLabel35.setText("Z");

        txt_G0Zf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G0Zf.setToolTipText("Posicion final en Z");
        txt_G0Zf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G0ZfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G0ZfFocusLost(evt);
            }
        });
        txt_G0Zf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G0ZfActionPerformed(evt);
            }
        });

        jLabel2.setText("Modo:");

        cbx_PosFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambos a la vez", "Primero X luego Z", "Primero Z luego X" }));
        cbx_PosFinal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_PosFinalItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_G0Xf, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_G0Zf, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx_PosFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbx_PosFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_G0Xf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(txt_G0Zf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel24.setText("[mm]");

        jLabel25.setText("[mm]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btn_Cancelar))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_F, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(301, 301, 301))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel20)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_Ap, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel22))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel26)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_U, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel24)))
                                    .addGap(47, 47, 47)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel21)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_R, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel23))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel27)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_W, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel25))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_Des)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(txt_Ap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txt_U, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_W, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txt_F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_Aceptar)
                                    .addComponent(btn_Cancelar))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ApFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ApFocusGained
        txt_Ap.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_ApFocusGained

    private void txt_ApFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ApFocusLost
        txt_Ap.setBackground(Color.white);
    }//GEN-LAST:event_txt_ApFocusLost

    private void txt_ApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApActionPerformed
        txt_Ap.transferFocus();
    }//GEN-LAST:event_txt_ApActionPerformed

    private void txt_RFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RFocusGained
        txt_R.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_RFocusGained

    private void txt_RFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RFocusLost
        txt_R.setBackground(Color.white);
    }//GEN-LAST:event_txt_RFocusLost

    private void txt_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RActionPerformed
        txt_R.transferFocus();
    }//GEN-LAST:event_txt_RActionPerformed

    private void txt_FFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FFocusGained
        txt_F.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_FFocusGained

    private void txt_FFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FFocusLost
        txt_F.setBackground(Color.white);
    }//GEN-LAST:event_txt_FFocusLost

    private void txt_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FActionPerformed
        txt_F.transferFocus();
    }//GEN-LAST:event_txt_FActionPerformed

    private void txt_UFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_UFocusGained
        txt_U.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_UFocusGained

    private void txt_UFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_UFocusLost
        String linea, arr[];
        arr = txt_U.getText().split("-");
        if (!Herramienta.IntExt) {
            if (arr.length >= 2) {
                txt_U.setText(arr[1]);
            }
        } else {
            if (arr.length == 1) {
                linea = "-" + txt_U.getText();
                txt_U.setText(linea);
            }
        }
        txt_U.setBackground(Color.white);
    }//GEN-LAST:event_txt_UFocusLost

    private void txt_UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UActionPerformed
        String linea, arr[];
        arr = txt_U.getText().split("-");
        if (!Herramienta.IntExt) {
            if (arr.length >= 2) {
                txt_U.setText(arr[1]);
            }
        } else {
            if (arr.length == 1) {
                linea = "-" + txt_U.getText();
                txt_U.setText(linea);
            }
        }
        txt_U.transferFocus();
    }//GEN-LAST:event_txt_UActionPerformed

    private void txt_WFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_WFocusGained
        txt_W.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_WFocusGained

    private void txt_WFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_WFocusLost
        txt_W.setBackground(Color.white);
    }//GEN-LAST:event_txt_WFocusLost

    private void txt_WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_WActionPerformed
        txt_W.transferFocus();
    }//GEN-LAST:event_txt_WActionPerformed

    private void ckb_AcabadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_AcabadoItemStateChanged
        if (!ckb_Acabado.isSelected()) {
            txt_AcS.setText("");
            txt_AcF.setText("");
//            ckb_AcComp.setSelected(ckb_Ac.isSelected());
        }
        txt_AcS.setEnabled(ckb_Acabado.isSelected());
        txt_AcF.setEnabled(ckb_Acabado.isSelected());
//        ckb_AcComp.setEnabled(ckb_Ac.isSelected());
    }//GEN-LAST:event_ckb_AcabadoItemStateChanged

    private void txt_AcSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_AcSFocusGained
        txt_AcS.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_AcSFocusGained

    private void txt_AcSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_AcSFocusLost
        txt_AcS.setBackground(Color.white);
    }//GEN-LAST:event_txt_AcSFocusLost

    private void txt_AcSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AcSActionPerformed
        txt_AcS.transferFocus();
    }//GEN-LAST:event_txt_AcSActionPerformed

    private void txt_PerfilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PerfilKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_Perfil.setText(txt_Perfil.getText().toUpperCase());
        }
    }//GEN-LAST:event_txt_PerfilKeyReleased

    private void txt_G0XfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0XfFocusGained
        txt_G0Xf.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G0XfFocusGained

    private void txt_G0XfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0XfFocusLost
        txt_G0Xf.setBackground(Color.white);
    }//GEN-LAST:event_txt_G0XfFocusLost

    private void txt_G0XfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G0XfActionPerformed
        txt_G0Xf.transferFocus();
    }//GEN-LAST:event_txt_G0XfActionPerformed

    private void txt_G0ZfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0ZfFocusGained
        txt_G0Zf.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G0ZfFocusGained

    private void txt_G0ZfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0ZfFocusLost
        txt_G0Zf.setBackground(Color.white);
    }//GEN-LAST:event_txt_G0ZfFocusLost

    private void txt_G0ZfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G0ZfActionPerformed
        txt_G0Zf.transferFocus();
    }//GEN-LAST:event_txt_G0ZfActionPerformed

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        String arr[], brr[], linea;
        if (rdb_G97.isSelected()) {
            if (!txt_G97S.getText().equals("")) {
                Velocidad = "G97 M3 S" + txt_G97S.getText() + ";" + '\n';
            } else {
                Velocidad = "";
            }
        } else {
            if (!txt_G96S.getText().equals("")) {
                Velocidad = "G96 M3 S" + txt_G96S.getText() + ";" + '\n';
            } else {
                Velocidad = "";
            }
        }
        if (!Herramienta.IntExt) {
            if (ckb_Compenzacion.isSelected()) {
                PosIni = "G0 G42 X" + txt_G0iniX.getText() + ";" + '\n';
            } else {
                PosIni = "G0 X" + txt_G0iniX.getText() + ";" + '\n';
            }            
        }else{
            if (ckb_Compenzacion.isSelected()) {
                PosIni = "G0 G41 X" + txt_G0iniX.getText() + ";" + '\n';
            } else {
                PosIni = "G0 X" + txt_G0iniX.getText() + ";" + '\n';
            }             
        }
        PosIni = PosIni + "Z" + txt_G0iniZ.getText();
        if (ckb_Refrigerante.isSelected()) {
            PosIni = PosIni + " M8;" + '\n';
        } else {
            PosIni = PosIni + ";" + '\n';
        }
//        if (!Herramienta.IntExt) {
//            if (ckb_Ac.isSelected()) {
//                PosIniAc = "G0 G41 X" + txt_AcG0Xi.getText() + " Z" + txt_AcG0Zi.getText() + ";" + '\n';
//            } else {
//                PosIniAc = "G0 X" + txt_AcG0Xi.getText() + " Z" + txt_AcG0Zi.getText() + ";" + '\n';
//            }
//        } else {
//            if (ckb_Ac.isSelected()) {
//                PosIniAc = "G0 G42 X" + txt_AcG0Xi.getText() + " Z" + txt_AcG0Zi.getText() + ";" + '\n';
//            } else {
//                PosIniAc = "G0 X" + txt_AcG0Xi.getText() + " Z" + txt_AcG0Zi.getText() + ";" + '\n';
//            }
//        }
        switch (modoFinal) {
            case 0:
                if (!txt_G0Xf.getText().equals("") && !txt_G0Zf.getText().equals("")) {
                    if (ckb_Compenzacion.isSelected()) {
                        PosFin = "G0 G40 X" + txt_G0Xf.getText() + " Z" + txt_G0Zf.getText();
                    } else {
                        PosFin = "G0 X" + txt_G0Xf.getText() + " Z" + txt_G0Zf.getText();
                    }
                } else {
                    JOptionPane.showConfirmDialog(this, "Debe ingresar X final y Z final", "FALA POSICION FINAL", JOptionPane.CLOSED_OPTION);
                    return;
                }
                break;
            case 1:
                if (!txt_G0Xf.getText().equals("")) {
                    if (!txt_G0Zf.getText().equals("")) {
                        if (ckb_Compenzacion.isSelected()) {
                            PosFin = "G0 G40 X" + txt_G0Xf.getText() + ";" + '\n' + "Z" + txt_G0Zf.getText();
                        } else {
                            PosFin = "G0 X" + txt_G0Xf.getText() + ";" + '\n' + "Z" + txt_G0Zf.getText();
                        }
                    } else {
                        if (ckb_Compenzacion.isSelected()) {
                            PosFin = "G0 G40 X" + txt_G0Xf.getText();
                        } else {
                            PosFin = "G0 X" + txt_G0Xf.getText();
                        }
                    }
                } else {
                    JOptionPane.showConfirmDialog(this, "Debe ingresar X final", "FALA POSICION FINAL", JOptionPane.CLOSED_OPTION);
                    return;
                }
                break;
            case 2:
                if (!txt_G0Zf.getText().equals("")) {
                    if (!txt_G0Xf.getText().equals("")) {
                        if (ckb_Compenzacion.isSelected()) {
                            PosFin = "G0 G40 Z" + txt_G0Zf.getText() + ";" + '\n' + "X" + txt_G0Xf.getText();
                        } else {
                            PosFin = "G0 Z" + txt_G0Zf.getText() + ";" + '\n' + "X" + txt_G0Xf.getText();
                        }
                    } else {
                        if (ckb_Compenzacion.isSelected()) {
                            PosFin = "G0 G40 Z" + txt_G0Zf.getText();
                        } else {
                            PosFin = "G0 Z" + txt_G0Zf.getText();
                        }
                    }
                } else {
                    JOptionPane.showConfirmDialog(this, "Debe ingresar Z final", "FALA POSICION FINAL", JOptionPane.CLOSED_OPTION);
                    return;
                }
                break;
        }
        if (ckb_Refrigerante.isSelected()) {
            PosFin = PosFin + " M9;" + '\n';
        } else {
            PosFin = PosFin + ";" + '\n';
        }
        Inicial.N++;
        linea = txt_Perfil.getText() + '\n';
        arr = linea.split("\n");
        brr = arr[0].split("G0");
        if (brr.length == 1) {
            linea = arr[0];
            arr[0] = "N" + String.valueOf(Inicial.N) + " G0 " + linea;
        }
        brr = arr[1].split("G1");
        if (brr.length == 1) {
            linea = arr[1];
            arr[1] = "G1 " + linea;
        }
        Inicial.N++;
        linea = arr[arr.length - 1];
        arr[arr.length - 1] = "N" + String.valueOf(Inicial.N) + " " + linea;
        Perfil = "";
        for (int i = 0; i < arr.length; i++) {
            Perfil = Perfil + arr[i] + ";" + '\n';
        }
        if (!txt_Des.getText().equals("")) {
            Principal.Procesos = Principal.Procesos + "(" + txt_Des.getText() + ");" + '\n';
        }
        Principal.Procesos = Principal.Procesos + Velocidad;
        Principal.Procesos = Principal.Procesos + PosIni;
        Principal.Procesos = Principal.Procesos + "G71 U" + txt_Ap.getText() + " R" + txt_R.getText() + ";" + '\n';
        Principal.Procesos = Principal.Procesos + "G71 P" + String.valueOf(Inicial.N - 1) + " Q" + String.valueOf(Inicial.N) + " U" + txt_U.getText() + " W" + txt_W.getText() + " F" + txt_F.getText() + ";" + '\n';
        Principal.Procesos = Principal.Procesos + Perfil;
        if (ckb_Acabado.isSelected()) {
            Principal.Procesos = Principal.Procesos + "S" + txt_AcS.getText() + ";" + '\n';
            if (ckb_Compenzacion.isSelected()) {
                Principal.Procesos = Principal.Procesos + PosIniAc;
            }
            Principal.Procesos = Principal.Procesos + "G70 P" + String.valueOf(Inicial.N - 1) + " Q" + String.valueOf(Inicial.N) + " F" + txt_AcF.getText() + ";" + '\n';
        }
        Principal.Procesos = Principal.Procesos + PosFin;
        Inicial.Herr = true;
        this.dispose();
    }//GEN-LAST:event_btn_AceptarActionPerformed

    private void txt_DesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DesFocusGained
        txt_Des.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_DesFocusGained

    private void txt_DesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DesFocusLost
        txt_Des.setBackground(Color.white);
        txt_Des.setText(txt_Des.getText().toUpperCase());
    }//GEN-LAST:event_txt_DesFocusLost

    private void txt_DesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DesActionPerformed
        txt_Des.setText(txt_Des.getText().toUpperCase());
        txt_Des.transferFocus();
    }//GEN-LAST:event_txt_DesActionPerformed

    private void rdb_G50ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdb_G50ItemStateChanged
        if (!rdb_G50.isSelected()) {
            txt_G96S.setText("");
        }
        txt_G96S.setEnabled(rdb_G50.isSelected());
    }//GEN-LAST:event_rdb_G50ItemStateChanged

    private void rdb_G97ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdb_G97ItemStateChanged
        if (!rdb_G97.isSelected()) {
            txt_G97S.setText("");
        }
        txt_G97S.setEnabled(rdb_G97.isSelected());
    }//GEN-LAST:event_rdb_G97ItemStateChanged

    private void txt_G97SFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G97SFocusGained
        txt_G97S.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G97SFocusGained

    private void txt_G97SFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G97SFocusLost
        txt_G97S.setBackground(Color.white);
    }//GEN-LAST:event_txt_G97SFocusLost

    private void txt_G97SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G97SActionPerformed
        txt_G97S.transferFocus();
    }//GEN-LAST:event_txt_G97SActionPerformed

    private void txt_G96SFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G96SFocusGained
        txt_G96S.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G96SFocusGained

    private void txt_G96SFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G96SFocusLost
        txt_G96S.setBackground(Color.white);
    }//GEN-LAST:event_txt_G96SFocusLost

    private void txt_G96SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G96SActionPerformed
        txt_G96S.transferFocus();
    }//GEN-LAST:event_txt_G96SActionPerformed

    private void txt_G0iniXFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0iniXFocusGained
        txt_G0iniX.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G0iniXFocusGained

    private void txt_G0iniXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0iniXFocusLost
        txt_G0iniX.setBackground(Color.white);
    }//GEN-LAST:event_txt_G0iniXFocusLost

    private void txt_G0iniXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G0iniXActionPerformed
        txt_G0iniX.transferFocus();
    }//GEN-LAST:event_txt_G0iniXActionPerformed

    private void txt_G0iniZFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0iniZFocusGained
        txt_G0iniZ.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G0iniZFocusGained

    private void txt_G0iniZFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0iniZFocusLost
        txt_G0iniZ.setBackground(Color.white);
    }//GEN-LAST:event_txt_G0iniZFocusLost

    private void txt_G0iniZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G0iniZActionPerformed
        txt_G0iniZ.transferFocus();
    }//GEN-LAST:event_txt_G0iniZActionPerformed

    private void txt_AcFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_AcFFocusGained
        txt_AcF.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_AcFFocusGained

    private void txt_AcFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_AcFFocusLost
        txt_AcF.setBackground(Color.white);
    }//GEN-LAST:event_txt_AcFFocusLost

    private void txt_AcFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AcFActionPerformed
        txt_AcF.transferFocus();
    }//GEN-LAST:event_txt_AcFActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularActionPerformed
        new CalculoVelocidades(null, true).setVisible(true);
    }//GEN-LAST:event_btn_CalcularActionPerformed

    private void cbx_PosFinalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_PosFinalItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            modoFinal = cbx_PosFinal.getSelectedIndex();
        }
    }//GEN-LAST:event_cbx_PosFinalItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cilindrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cilindrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cilindrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cilindrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cilindrado dialog = new Cilindrado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_Calcular;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbx_PosFinal;
    private javax.swing.JCheckBox ckb_Acabado;
    private javax.swing.JCheckBox ckb_Compenzacion;
    private javax.swing.JCheckBox ckb_Refrigerante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdb_G50;
    private javax.swing.JRadioButton rdb_G97;
    private javax.swing.JTextField txt_AcF;
    private javax.swing.JTextField txt_AcS;
    private javax.swing.JTextField txt_Ap;
    private javax.swing.JTextArea txt_Ayuda;
    private javax.swing.JTextField txt_Des;
    private javax.swing.JTextField txt_F;
    private javax.swing.JTextField txt_G0Xf;
    private javax.swing.JTextField txt_G0Zf;
    private javax.swing.JTextField txt_G0iniX;
    private javax.swing.JTextField txt_G0iniZ;
    private javax.swing.JTextField txt_G96S;
    private javax.swing.JTextField txt_G97S;
    private javax.swing.JTextArea txt_Perfil;
    private javax.swing.JTextField txt_R;
    private javax.swing.JTextField txt_U;
    private javax.swing.JTextField txt_W;
    // End of variables declaration//GEN-END:variables
}
