/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pqt;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo A. Di Iorio
 */
public class Inicial extends javax.swing.JDialog {

    static public boolean Herr = false;
    static public int N = 0;
    String unidadMedida = "";
    String avance = "";
    String compenzacion = "";
    String coordenada = "G54";
    String referencia = "";
    String Vc = "";

    /**
     * Creates new form Ini
     */
    public Inicial(java.awt.Frame parent, boolean modal) throws IOException {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Configuracion inicial del programa");
        Limpiar();
    }
    /**
     * Actualiza el textArea cuando hay cambios
     */
    private void ActualizarEncabezado() {
        String codigo = "";
        txt_Encabezado.setText("");
        codigo = "O" + txt_NProg.getText() + " (" + txt_Nombre.getText() + ");" + '\n';
        codigo = codigo + unidadMedida + avance + coordenada;
        if (!compenzacion.equals("")) {
            codigo = codigo + " " + compenzacion + ";" + '\n';
        } else {
            codigo = codigo + ";" + '\n';
        }
        codigo = codigo + referencia;
        codigo = codigo + Vc;
        txt_Encabezado.setText(codigo);
        Principal.NProg = txt_NProg.getText();
    }
    /**
     * Coloca la interfaz por default
     * @throws IOException 
     */
    private void Limpiar() throws IOException {
        File archivo;
        String dir;
        boolean existe = false;
        dir = System.getProperty("user.dir");
        archivo = new File(dir + "/Encabezado.txt");
        if (!archivo.exists()) {
            archivo = new File(getClass().getResource("/pqt/Encabezado.txt").getFile());
        }
        String linea = "", arr[];
        FileReader abrir = null;
        BufferedReader miBuffer = null;
        abrir = new FileReader(archivo.getAbsolutePath());
        miBuffer = new BufferedReader(abrir);
        linea = miBuffer.readLine();
        arr = linea.split("=");
        if (arr[1].equals("mm")) {
            btg_MM.setSelected(true);
            unidadMedida = "G21 ";
        } else {
            btg_INCH.setSelected(true);
            unidadMedida = "G20 ";
        }
        linea = miBuffer.readLine();
        arr = linea.split("=");
        if (arr[1].equals("rev")) {
            btg_MmRev.setSelected(true);
            avance = "G99 ";
        } else {
            btg_MmMin.setSelected(true);
            avance = "G98 ";
        }
        linea = miBuffer.readLine();
        arr = linea.split("=");
        cbx_Coordenada.setSelectedIndex(Integer.parseInt(arr[1]));
        coordenada = "G5" + String.valueOf(Integer.parseInt(arr[1]) + 4);
        linea = miBuffer.readLine();
        arr = linea.split("=");
        if (arr[1].equals("0")) {
            ckb_G40.setSelected(false);
            compenzacion = "";
        } else {
            ckb_G40.setSelected(true);
            compenzacion = "G40";
        }
        linea = miBuffer.readLine();
        arr = linea.split("=");
        if (arr[1].equals("1")) {
            ckb_Referencia.setSelected(true);
            referencia = "G28 U0 W0;" + '\n';
        } else {
            ckb_Referencia.setSelected(false);
            referencia = "";
        }
        linea = miBuffer.readLine();
        arr = linea.split("=");
        if (arr[1].equals("1")) {
            ckb_LimSpeed.setSelected(true);
            linea = miBuffer.readLine();
            arr = linea.split("=");
            txt_S.setText(arr[1]);
            Vc = "G50 S" + txt_S.getText() + ";" + '\n';
            Principal.G50 = true;
        } else {
            ckb_LimSpeed.setSelected(false);
            txt_S.setText("");
            Vc = "";
            Principal.G50 = false;
        }
        abrir.close();
        ActualizarEncabezado();
        txt_NProg.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        btn_Aceptar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        txt_NProg = new javax.swing.JTextField();
        btn_Herr = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btg_MM = new javax.swing.JRadioButton();
        btg_INCH = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btg_MmRev = new javax.swing.JRadioButton();
        btg_MmMin = new javax.swing.JRadioButton();
        ckb_G40 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        ckb_LimSpeed = new javax.swing.JCheckBox();
        txt_S = new javax.swing.JTextField();
        ckb_Referencia = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Encabezado = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        cbx_Coordenada = new javax.swing.JComboBox<>();
        btn_Predefinir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("N° de programa: O");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        txt_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_Nombre.setToolTipText("Nombre descriptivo del programa");
        txt_Nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_NombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_NombreFocusLost(evt);
            }
        });
        txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombreActionPerformed(evt);
            }
        });

        btn_Aceptar.setText("Aceptar");
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        txt_NProg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_NProg.setToolTipText("Numero de programa de 4 digitos");
        txt_NProg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_NProgFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_NProgFocusLost(evt);
            }
        });
        txt_NProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NProgActionPerformed(evt);
            }
        });

        btn_Herr.setText("Agregar Herramienta");
        btn_Herr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HerrActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Unidades:");

        buttonGroup1.add(btg_MM);
        btg_MM.setText("Milimetros");
        btg_MM.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btg_MMItemStateChanged(evt);
            }
        });

        buttonGroup1.add(btg_INCH);
        btg_INCH.setSelected(true);
        btg_INCH.setText("Pulgadas");
        btg_INCH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btg_INCHItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btg_INCH)
                            .addComponent(btg_MM))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btg_MM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btg_INCH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Avance:");

        buttonGroup2.add(btg_MmRev);
        btg_MmRev.setText("[mm/rev]");
        btg_MmRev.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btg_MmRevItemStateChanged(evt);
            }
        });

        buttonGroup2.add(btg_MmMin);
        btg_MmMin.setSelected(true);
        btg_MmMin.setText("[mm/min]");
        btg_MmMin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btg_MmMinItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btg_MmMin)
                            .addComponent(btg_MmRev))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btg_MmRev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btg_MmMin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ckb_G40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckb_G40.setText("Anular la compenzacion del radio de la herramienta");
        ckb_G40.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_G40ItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("[RPM]");

        ckb_LimSpeed.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckb_LimSpeed.setSelected(true);
        ckb_LimSpeed.setText("Limitar velocidad de husillo a");
        ckb_LimSpeed.setToolTipText("Limita la velocidad del husillo");
        ckb_LimSpeed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_LimSpeedItemStateChanged(evt);
            }
        });

        txt_S.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_S.setToolTipText("Maximas rpm del husillo cuando se aplica el limite de velocidad");
        txt_S.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_SFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_SFocusLost(evt);
            }
        });
        txt_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SActionPerformed(evt);
            }
        });

        ckb_Referencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckb_Referencia.setSelected(true);
        ckb_Referencia.setText("Volver a Referencia");
        ckb_Referencia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckb_ReferenciaItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Encabezado:");

        txt_Encabezado.setColumns(20);
        txt_Encabezado.setRows(5);
        jScrollPane1.setViewportView(txt_Encabezado);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Seleccion del sistema de coordenadas");

        cbx_Coordenada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbx_Coordenada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pieza 1", "Pieza 2", "Pieza 3", "Pieza 4", "Pieza 5", "Pieza 6" }));
        cbx_Coordenada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_CoordenadaItemStateChanged(evt);
            }
        });

        btn_Predefinir.setText("Predefinir");
        btn_Predefinir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PredefinirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx_Coordenada, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ckb_Referencia)
                            .addComponent(ckb_G40)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ckb_LimSpeed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_S, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btn_Predefinir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbx_Coordenada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckb_G40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckb_Referencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckb_LimSpeed)
                    .addComponent(txt_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Predefinir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_NProg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Nombre))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btn_Herr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Aceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Cancelar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_NProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Aceptar)
                    .addComponent(btn_Cancelar)
                    .addComponent(btn_Herr))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        if (!Herr) {
            JOptionPane.showConfirmDialog(this, "No se ha agregado operacion para la herramienta", "Debe elejir operacion", JOptionPane.CLOSED_OPTION);
        } else {
            if (txt_NProg.getText().equals("") || (txt_NProg.getText().length() <= 3)) {
                JOptionPane.showConfirmDialog(this, "Debe introducir un numero de 4 cifras en N° de programa", "Falta numero de programa", JOptionPane.CLOSED_OPTION);
            } else {
                ActualizarEncabezado();
                Principal.Encabezado = txt_Encabezado.getText();
                this.dispose();
            }
        }
    }//GEN-LAST:event_btn_AceptarActionPerformed

    private void txt_NProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NProgActionPerformed
        String str = "", linea;
        linea = txt_NProg.getText();
        if (linea.length() <= 3) {
            for (int i = 0; i < (4 - linea.length()); i++) {
                str = str + "0";
            }
            txt_NProg.setText(str + linea);
        } else if (linea.length() >= 5) {
            linea = linea.substring(0, 4);
            txt_NProg.setText(linea);
        }
        txt_NProg.transferFocus();
        ActualizarEncabezado();
    }//GEN-LAST:event_txt_NProgActionPerformed

    private void btn_HerrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HerrActionPerformed
        if (ckb_LimSpeed.isSelected() && !txt_S.getText().equals("")) {
            Principal.G50 = true;
        } else {
            Principal.G50 = false;
        }
        new Herramienta(null, true).setVisible(true);
    }//GEN-LAST:event_btn_HerrActionPerformed

    private void txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombreActionPerformed
        txt_Nombre.setText(txt_Nombre.getText().toUpperCase());
        txt_Nombre.transferFocus();
        ActualizarEncabezado();
    }//GEN-LAST:event_txt_NombreActionPerformed

    private void txt_NProgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NProgFocusGained
        txt_NProg.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_NProgFocusGained

    private void txt_NProgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NProgFocusLost
        txt_NProg.setBackground(Color.WHITE);
    }//GEN-LAST:event_txt_NProgFocusLost

    private void txt_NombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NombreFocusGained
        txt_Nombre.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_NombreFocusGained

    private void txt_NombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NombreFocusLost
        txt_Nombre.setBackground(Color.WHITE);
        txt_Nombre.setText(txt_Nombre.getText().toUpperCase());
    }//GEN-LAST:event_txt_NombreFocusLost

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        Principal.Codigo = "";
        Principal.Encabezado = "";
        Principal.Herramienta = "";
        Principal.Procesos = "";
        Principal.NProg = "";
        this.dispose();
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void cbx_CoordenadaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_CoordenadaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (cbx_Coordenada.getSelectedIndex() != -1) {
                coordenada = "G5" + String.valueOf(cbx_Coordenada.getSelectedIndex() + 4);
                ActualizarEncabezado();
            }
        }
    }//GEN-LAST:event_cbx_CoordenadaItemStateChanged

    private void ckb_ReferenciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_ReferenciaItemStateChanged
        if (ckb_Referencia.isSelected()) {
            referencia = "G28 U0 W0;" + '\n';
        } else {
            referencia = "";
        }
        ActualizarEncabezado();
    }//GEN-LAST:event_ckb_ReferenciaItemStateChanged

    private void txt_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SActionPerformed
        Vc = "G50 S" + txt_S.getText() + ";" + '\n';
        ActualizarEncabezado();
        txt_S.transferFocus();
    }//GEN-LAST:event_txt_SActionPerformed

    private void txt_SFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_SFocusLost
        txt_S.setBackground(Color.WHITE);
    }//GEN-LAST:event_txt_SFocusLost

    private void txt_SFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_SFocusGained
        txt_S.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_SFocusGained

    private void ckb_LimSpeedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_LimSpeedItemStateChanged
        if (!ckb_LimSpeed.isSelected()) {
            txt_S.setText("");
            Vc = "";
        }
        txt_S.setEnabled(ckb_LimSpeed.isSelected());
        ActualizarEncabezado();
    }//GEN-LAST:event_ckb_LimSpeedItemStateChanged

    private void ckb_G40ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckb_G40ItemStateChanged
       if (ckb_G40.isSelected()) {
            compenzacion = "G40";
        } else {
            compenzacion = "";
        }
        ActualizarEncabezado();
    }//GEN-LAST:event_ckb_G40ItemStateChanged

    private void btg_MmMinItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btg_MmMinItemStateChanged
        avance = "G98 ";
        ActualizarEncabezado();
    }//GEN-LAST:event_btg_MmMinItemStateChanged

    private void btg_MmRevItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btg_MmRevItemStateChanged
        avance = "G99 ";
        ActualizarEncabezado();
    }//GEN-LAST:event_btg_MmRevItemStateChanged

    private void btg_INCHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btg_INCHItemStateChanged
        unidadMedida = "G20 ";
        ActualizarEncabezado();
    }//GEN-LAST:event_btg_INCHItemStateChanged

    private void btg_MMItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btg_MMItemStateChanged
        unidadMedida = "G21 ";
        ActualizarEncabezado();
    }//GEN-LAST:event_btg_MMItemStateChanged

    private void btn_PredefinirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PredefinirActionPerformed
        File archivo;
        String dir;
        boolean existe = false;
        dir = System.getProperty("user.dir");
        archivo = new File(dir + "/Encabezado.txt");
        if (archivo.exists()) {
            existe = true;
        } else {
            existe = false;
            archivo = new File(getClass().getResource("/pqt/Encabezado.txt").getFile());
        }
        PrintWriter salida = null;
        try {
            salida = new PrintWriter(archivo.getAbsolutePath());
            if (btg_MM.isSelected()) {
                salida.println("Unidades=mm");
            } else {
                salida.println("Unidades=in");
            }
            if (btg_MmRev.isSelected()) {
                salida.println("Avance=rev");
            } else {
                salida.println("Avance=min");
            }
            salida.println("Coordenadas=" + String.valueOf(cbx_Coordenada.getSelectedIndex()));
            if (ckb_G40.isSelected()) {
                salida.println("G40=1");
            } else {
                salida.println("G40=0");
            }
            if (ckb_Referencia.isSelected()) {
                salida.println("G28=1");
            } else {
                salida.println("G28=0");
            }
            if (ckb_LimSpeed.isSelected()) {
                salida.println("G50=1");
                salida.println("S=" + txt_S.getText());
            } else {
                salida.println("G50=0");
                salida.println("S=0");
            }
            salida.close();
            JOptionPane.showConfirmDialog(this, "Se han guardado correctamente los valores predeterminados", "Valores predeterminados", JOptionPane.CLOSED_OPTION);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Inicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_PredefinirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inicial dialog = null;
                try {
                    dialog = new Inicial(new javax.swing.JFrame(), true);
                } catch (IOException ex) {
                    Logger.getLogger(Inicial.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btg_INCH;
    private javax.swing.JRadioButton btg_MM;
    private javax.swing.JRadioButton btg_MmMin;
    private javax.swing.JRadioButton btg_MmRev;
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Herr;
    private javax.swing.JButton btn_Predefinir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cbx_Coordenada;
    private javax.swing.JCheckBox ckb_G40;
    private javax.swing.JCheckBox ckb_LimSpeed;
    private javax.swing.JCheckBox ckb_Referencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_Encabezado;
    private javax.swing.JTextField txt_NProg;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_S;
    // End of variables declaration//GEN-END:variables
}
