/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pqt;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Interpolacion extends javax.swing.JDialog {

    String Velocidad = "";
    String PosIni = "";
    String PosFin = "";
    String Perfil = "";
    int modoFinal = 0;

    /**
     * Creates new form Inter
     */
    public Interpolacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Movimiento de mecanizado simple");
        rdb_G50.setSelected(Principal.G50);
        rdb_G50.setEnabled(Principal.G50);
        rdb_G97.setSelected(!Principal.G50);
        txt_G96S.setEnabled(Principal.G50);
        String ayuda = "* G0= movimiento rápido sin mecanizar" + '\n'
                + '\t' + "G0 Xx Zz" + '\n'
                + '\t' + '\t' + "x: posición final" + '\n'
                + '\t' + '\t' + "z: longitud final" + '\n' + '\n'
                + "* G1= interpolacion lineal:" + '\n'
                + '\t' + "G1 Xx Zz Ff" + '\n'
                + '\t' + '\t' + "x: diámetro final" + '\n'
                + '\t' + '\t' + "z: longitud final" + '\n'
                + '\t' + '\t' + "f: velocidad de avance" + '\n' + '\n'
                + "* G2= interpolacion circular en sentido horario:" + '\n'
                + '\t' + "G2 Xx Zz Rr Ff" + '\n'
                + '\t' + '\t' + "x: diámetro final" + '\n'
                + '\t' + '\t' + "z: posición final" + '\n'
                + '\t' + '\t' + "r: radio de la curva" + '\n'
                + '\t' + '\t' + "f: velocidad de avance" + '\n' + '\n'
                + "* G3= interpolacion circular en sentido antihorario:" + '\n'
                + '\t' + "G3 Xx Zz Rr Ff" + '\n'
                + '\t' + '\t' + "x: diámetro final" + '\n'
                + '\t' + '\t' + "z: posición final" + '\n'
                + '\t' + '\t' + "r: radio de la curva" + '\n'
                + '\t' + '\t' + "f: velocidad de avance" + '\n';
        txt_Ayuda.setText(ayuda);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel36 = new javax.swing.JLabel();
        txt_Des = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rdb_G50 = new javax.swing.JRadioButton();
        rdb_G97 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_G97S = new javax.swing.JTextField();
        txt_G96S = new javax.swing.JTextField();
        btn_Calcular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_G0iniX = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_G0iniZ = new javax.swing.JTextField();
        ckb_Refrigerante = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_F = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Perfil = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_G0finX = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_G0finZ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbx_PosFinal = new javax.swing.JComboBox<>();
        btn_Cancelar = new javax.swing.JButton();
        btn_Aceptar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Ayuda = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel36.setText("Descripcion:");

        txt_Des.setToolTipText("Nombre descriptivo del proceso");
        txt_Des.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_DesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_DesFocusLost(evt);
            }
        });
        txt_Des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DesActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(rdb_G50);
        rdb_G50.setText("Velocidad de corte constante (G96):");
        rdb_G50.setToolTipText("Seleccione para velocidad de corte constante");
        rdb_G50.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdb_G50ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rdb_G97);
        rdb_G97.setSelected(true);
        rdb_G97.setText("Velocidad de cabezal constante (G97):");
        rdb_G97.setToolTipText("Seleccione para velocidad de husillo constante");
        rdb_G97.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdb_G97ItemStateChanged(evt);
            }
        });

        jLabel5.setText("Velocidad de corte:");

        jLabel6.setText("[m/min]");

        jLabel7.setText("[RPM]");

        jLabel9.setText("Velocidad:");

        txt_G97S.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G97S.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G97SFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G97SFocusLost(evt);
            }
        });
        txt_G97S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G97SActionPerformed(evt);
            }
        });

        txt_G96S.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G96S.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G96SFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G96SFocusLost(evt);
            }
        });
        txt_G96S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G96SActionPerformed(evt);
            }
        });

        btn_Calcular.setText("Calcular");
        btn_Calcular.setFocusable(false);
        btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdb_G50)
                    .addComponent(rdb_G97)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_G97S, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Calcular))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_G96S, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdb_G50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txt_G96S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdb_G97)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(txt_G97S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Calcular))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Posicionamiento inicial:");

        jLabel11.setText("X");

        txt_G0iniX.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G0iniX.setToolTipText("Posicion de seguridad en X");
        txt_G0iniX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G0iniXFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G0iniXFocusLost(evt);
            }
        });
        txt_G0iniX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G0iniXActionPerformed(evt);
            }
        });

        jLabel12.setText("Z");

        txt_G0iniZ.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G0iniZ.setToolTipText("Posicion de seguridad en Z");
        txt_G0iniZ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G0iniZFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G0iniZFocusLost(evt);
            }
        });
        txt_G0iniZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G0iniZActionPerformed(evt);
            }
        });

        ckb_Refrigerante.setText("Refrigerante On/Off");
        ckb_Refrigerante.setToolTipText("Seleccione para activar el refrigerante");

        jLabel1.setText("Velocidad de avance:");

        jLabel2.setText("F");

        txt_F.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_F.setToolTipText("Velocidad de avance");
        txt_F.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_FFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_FFocusLost(evt);
            }
        });
        txt_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FActionPerformed(evt);
            }
        });

        jLabel3.setText("[mm/rev]");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_F, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_G0iniZ, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_G0iniX, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckb_Refrigerante)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_G0iniX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_G0iniZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckb_Refrigerante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_Perfil.setColumns(20);
        txt_Perfil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Perfil.setRows(5);
        txt_Perfil.setToolTipText("Ingrese los movimienos en G0, G1, G2, G3 que desee realizar");
        txt_Perfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PerfilKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txt_Perfil);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("Posicionamiento final:");

        jLabel14.setText("X");

        txt_G0finX.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G0finX.setToolTipText("Posicion final en X");
        txt_G0finX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G0finXFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G0finXFocusLost(evt);
            }
        });
        txt_G0finX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G0finXActionPerformed(evt);
            }
        });

        jLabel15.setText("Z");

        txt_G0finZ.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G0finZ.setToolTipText("Posicion final en Z");
        txt_G0finZ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G0finZFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G0finZFocusLost(evt);
            }
        });
        txt_G0finZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G0finZActionPerformed(evt);
            }
        });

        jLabel4.setText("Modo:");

        cbx_PosFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambos a la vez", "Primero X luego Z", "Primero Z luego X" }));
        cbx_PosFinal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_PosFinalItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_PosFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_G0finX, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_G0finZ, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbx_PosFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_G0finX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_G0finZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        btn_Aceptar.setText("Aceptar");
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setHorizontalScrollBar(null);

        txt_Ayuda.setColumns(20);
        txt_Ayuda.setRows(5);
        txt_Ayuda.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_Ayuda.setEnabled(false);
        jScrollPane2.setViewportView(txt_Ayuda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Des, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_Des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btn_Aceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Cancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdb_G50ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdb_G50ItemStateChanged
        if (!rdb_G50.isSelected()) {
            txt_G96S.setText("");
        }
        txt_G96S.setEnabled(rdb_G50.isSelected());
    }//GEN-LAST:event_rdb_G50ItemStateChanged

    private void rdb_G97ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdb_G97ItemStateChanged
        if (!rdb_G97.isSelected()) {
            txt_G97S.setText("");
        }
        txt_G97S.setEnabled(rdb_G97.isSelected());
    }//GEN-LAST:event_rdb_G97ItemStateChanged

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        String arr[], brr[], linea;
        if (rdb_G97.isSelected()) {
            if (!txt_G97S.getText().equals("")) {
                Velocidad = "G97 M3 S" + txt_G97S.getText() + ";" + '\n';
            } else {
                Velocidad = "";
            }
        } else {
            if (!txt_G96S.getText().equals("")) {
                Velocidad = "G96 M3 S" + txt_G96S.getText() + ";" + '\n';
            } else {
                Velocidad = "";
            }
        }
        PosIni = "G0 X" + txt_G0iniX.getText() + ";" + '\n';
        PosIni = PosIni + "Z" + txt_G0iniZ.getText();
        if (ckb_Refrigerante.isSelected()) {
            PosIni = PosIni + " M8;" + '\n';
        } else {
            PosIni = PosIni + ";" + '\n';
        }
        linea = txt_Perfil.getText() + '\n';
        arr = linea.split("\n");
        brr = arr[0].split("G1");
        if (brr.length == 1) {
            brr = arr[0].split("G2");
            if (brr.length == 1) {
                brr = arr[0].split("G3");
                if (brr.length == 1) {
                    linea = arr[0];
                    arr[0] = "G1 " + linea;
                }
            }
        }
        arr[0] = arr[0] + " F" + txt_F.getText();
        Perfil = "";
        for (int i = 0; i < arr.length; i++) {
            Perfil = Perfil + arr[i] + ";" + '\n';
        }
        switch (modoFinal) {
            case 0:
                if (!txt_G0finX.getText().equals("") && !txt_G0finZ.getText().equals("")) {
                    PosFin = "G0 X" + txt_G0finX.getText() + " Z" + txt_G0finZ.getText();
                } else {
                    JOptionPane.showConfirmDialog(this, "Debe ingresar X final y Z final", "FALA POSICION FINAL", JOptionPane.CLOSED_OPTION);
                    return;
                }
                break;
            case 1:
                if (!txt_G0finX.getText().equals("")) {
                    if (!txt_G0finZ.getText().equals("")) {
                        PosFin = "G0 X" + txt_G0finX.getText() + ";" + '\n' + "Z" + txt_G0finZ.getText();
                    } else {
                        PosFin = "G0 X" + txt_G0finX.getText();
                    }
                } else {
                    JOptionPane.showConfirmDialog(this, "Debe ingresar X final", "FALA POSICION FINAL", JOptionPane.CLOSED_OPTION);
                    return;
                }
                break;
            case 2:
                if (!txt_G0finZ.getText().equals("")) {
                    if (!txt_G0finX.getText().equals("")) {
                        PosFin = "G0 Z" + txt_G0finZ.getText() + ";" + '\n' + "X" + txt_G0finX.getText();
                    } else {
                        PosFin = "G0 Z" + txt_G0finZ.getText();
                    }
                } else {
                    JOptionPane.showConfirmDialog(this, "Debe ingresar Z final", "FALA POSICION FINAL", JOptionPane.CLOSED_OPTION);
                    return;
                }
                break;
        }
        if (ckb_Refrigerante.isSelected()) {
            PosFin = PosFin + " M9;" + '\n';
        } else {
            PosFin = PosFin + ";" + '\n';
        }
        if (!txt_Des.getText().equals("")) {
            Principal.Procesos = Principal.Procesos + "(" + txt_Des.getText()+ ");" + '\n' + Velocidad + PosIni + Perfil + PosFin;
        } else {
            Principal.Procesos = Principal.Procesos + Velocidad + PosIni + Perfil + PosFin;
        }
        Inicial.Herr = true;
        this.dispose();
    }//GEN-LAST:event_btn_AceptarActionPerformed

    private void txt_G0iniXFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0iniXFocusGained
        txt_G0iniX.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G0iniXFocusGained

    private void txt_G0iniXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0iniXFocusLost
        txt_G0iniX.setBackground(Color.white);
    }//GEN-LAST:event_txt_G0iniXFocusLost

    private void txt_G0iniXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G0iniXActionPerformed
        txt_G0iniX.transferFocus();
    }//GEN-LAST:event_txt_G0iniXActionPerformed

    private void txt_G0iniZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G0iniZActionPerformed
        txt_G0iniZ.transferFocus();
    }//GEN-LAST:event_txt_G0iniZActionPerformed

    private void txt_G0iniZFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0iniZFocusGained
        txt_G0iniZ.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G0iniZFocusGained

    private void txt_G0iniZFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0iniZFocusLost
        txt_G0iniZ.setBackground(Color.white);
    }//GEN-LAST:event_txt_G0iniZFocusLost

    private void txt_G0finXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G0finXActionPerformed
        txt_G0finX.transferFocus();
    }//GEN-LAST:event_txt_G0finXActionPerformed

    private void txt_G0finZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G0finZActionPerformed
        txt_G0finZ.transferFocus();
    }//GEN-LAST:event_txt_G0finZActionPerformed

    private void txt_G0finXFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0finXFocusGained
        txt_G0finX.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G0finXFocusGained

    private void txt_G0finZFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0finZFocusGained
        txt_G0finZ.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G0finZFocusGained

    private void txt_G0finXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0finXFocusLost
        txt_G0finX.setBackground(Color.white);
    }//GEN-LAST:event_txt_G0finXFocusLost

    private void txt_G0finZFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0finZFocusLost
        txt_G0finZ.setBackground(Color.white);
    }//GEN-LAST:event_txt_G0finZFocusLost

    private void txt_PerfilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PerfilKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_Perfil.setText(txt_Perfil.getText().toUpperCase());
        }
    }//GEN-LAST:event_txt_PerfilKeyPressed

    private void txt_G97SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G97SActionPerformed
        txt_G97S.transferFocus();
    }//GEN-LAST:event_txt_G97SActionPerformed

    private void txt_G97SFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G97SFocusGained
        txt_G97S.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G97SFocusGained

    private void txt_G97SFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G97SFocusLost
        txt_G97S.setBackground(Color.white);
    }//GEN-LAST:event_txt_G97SFocusLost

    private void txt_G96SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G96SActionPerformed
        txt_G96S.transferFocus();
    }//GEN-LAST:event_txt_G96SActionPerformed

    private void txt_G96SFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G96SFocusGained
        txt_G96S.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G96SFocusGained

    private void txt_G96SFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G96SFocusLost
        txt_G96S.setBackground(Color.white);
    }//GEN-LAST:event_txt_G96SFocusLost

    private void txt_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FActionPerformed
        txt_F.transferFocus();
    }//GEN-LAST:event_txt_FActionPerformed

    private void txt_FFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FFocusGained
        txt_F.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_FFocusGained

    private void txt_FFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FFocusLost
        txt_F.setBackground(Color.white);
    }//GEN-LAST:event_txt_FFocusLost

    private void txt_DesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DesActionPerformed
        txt_Des.setText(txt_Des.getText().toUpperCase());
        txt_Des.transferFocus();
    }//GEN-LAST:event_txt_DesActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularActionPerformed
        new CalculoVelocidades(null, true).setVisible(true);
    }//GEN-LAST:event_btn_CalcularActionPerformed

    private void cbx_PosFinalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_PosFinalItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            modoFinal = cbx_PosFinal.getSelectedIndex();
        }
    }//GEN-LAST:event_cbx_PosFinalItemStateChanged

    private void txt_DesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DesFocusLost
        txt_Des.setBackground(Color.white);
        txt_Des.setText(txt_Des.getText().toUpperCase());
    }//GEN-LAST:event_txt_DesFocusLost

    private void txt_DesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DesFocusGained
        txt_Des.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_DesFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interpolacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interpolacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interpolacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interpolacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Interpolacion dialog = new Interpolacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_Calcular;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbx_PosFinal;
    private javax.swing.JCheckBox ckb_Refrigerante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdb_G50;
    private javax.swing.JRadioButton rdb_G97;
    private javax.swing.JTextArea txt_Ayuda;
    private javax.swing.JTextField txt_Des;
    private javax.swing.JTextField txt_F;
    private javax.swing.JTextField txt_G0finX;
    private javax.swing.JTextField txt_G0finZ;
    private javax.swing.JTextField txt_G0iniX;
    private javax.swing.JTextField txt_G0iniZ;
    private javax.swing.JTextField txt_G96S;
    private javax.swing.JTextField txt_G97S;
    private javax.swing.JTextArea txt_Perfil;
    // End of variables declaration//GEN-END:variables
}
