/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pqt;

import java.awt.Color;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Ranurado extends javax.swing.JDialog {

    String Velocidad = "";
    String PosIni = "";
    String PosFin = "";
    String Perfil = "";
    String PosFinAc = "";
    String PosIniAc = "";
    int modoFinal = 0;

    /**
     * Creates new form Ranurado
     */
    public Ranurado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        rdb_G50.setSelected(Principal.G50);
        rdb_G50.setEnabled(Principal.G50);
        rdb_G97.setSelected(!Principal.G50);
        txt_G96S.setEnabled(Principal.G50);
        this.setTitle("Ranurado longitudinal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel36 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_X = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_R = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_F = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_W = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_P = new javax.swing.JTextField();
        btn_Aceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_Des = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rdb_G50 = new javax.swing.JRadioButton();
        rdb_G97 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_G97S = new javax.swing.JTextField();
        txt_G96S = new javax.swing.JTextField();
        btn_Calcular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_G0iniX = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_G0iniZ = new javax.swing.JTextField();
        ckb_Refrigerante = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_Q = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbx_PosFinal = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        txt_G0Xf = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txt_G0Zf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel36.setText("Descripcion:");

        jLabel20.setText("Diametro final:");

        txt_X.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_X.setToolTipText("Diametro final de la ranura");
        txt_X.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_XFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_XFocusLost(evt);
            }
        });
        txt_X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_XActionPerformed(evt);
            }
        });

        jLabel22.setText("[mm]");

        jLabel21.setText("Retraccion:");

        txt_R.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_R.setToolTipText("Valor de retraccion de la herramienta luego de la pasada");
        txt_R.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_RFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_RFocusLost(evt);
            }
        });
        txt_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RActionPerformed(evt);
            }
        });

        jLabel23.setText("[mm]");

        jLabel28.setText("F");

        txt_F.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_F.setToolTipText("Velocidad de avance");
        txt_F.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_FFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_FFocusLost(evt);
            }
        });
        txt_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FActionPerformed(evt);
            }
        });

        jLabel1.setText("[mm/rev]");

        jLabel26.setText("Ancho de la ranura:");

        txt_W.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_W.setToolTipText("Ancho de la ranura. Debe tener en cuenta el ancho de la herramienta de corte");
        txt_W.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_WFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_WFocusLost(evt);
            }
        });
        txt_W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_WActionPerformed(evt);
            }
        });

        jLabel27.setText("Picoteo en X:");

        txt_P.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_P.setToolTipText("Profundidad radial del picoteo");
        txt_P.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_PFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_PFocusLost(evt);
            }
        });
        txt_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PActionPerformed(evt);
            }
        });

        btn_Aceptar.setText("Aceptar");
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        txt_Des.setToolTipText("Nombre descriptivo del proceso");
        txt_Des.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_DesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_DesFocusLost(evt);
            }
        });
        txt_Des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DesActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(rdb_G50);
        rdb_G50.setText("Velocidad de corte constante (G96):");
        rdb_G50.setToolTipText("Seleccione para velocidad de corte constante");
        rdb_G50.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdb_G50ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rdb_G97);
        rdb_G97.setSelected(true);
        rdb_G97.setText("Velocidad de cabezal constante (G97):");
        rdb_G97.setToolTipText("Seleccione para velocidad de husillo constante");
        rdb_G97.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdb_G97ItemStateChanged(evt);
            }
        });

        jLabel5.setText("Velocidad de corte:");

        jLabel6.setText("[m/min]");

        jLabel7.setText("[RPM]");

        jLabel9.setText("Velocidad:");

        txt_G97S.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G97S.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G97SFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G97SFocusLost(evt);
            }
        });
        txt_G97S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G97SActionPerformed(evt);
            }
        });

        txt_G96S.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G96S.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G96SFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G96SFocusLost(evt);
            }
        });
        txt_G96S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G96SActionPerformed(evt);
            }
        });

        btn_Calcular.setText("Calcular");
        btn_Calcular.setFocusable(false);
        btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdb_G50)
                    .addComponent(rdb_G97)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_G97S, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Calcular))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_G96S, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdb_G50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txt_G96S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdb_G97)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(txt_G97S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Calcular))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Posicionamiento inicial:");

        jLabel11.setText("X");

        txt_G0iniX.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G0iniX.setToolTipText("Posicion de seguridad en X");
        txt_G0iniX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G0iniXFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G0iniXFocusLost(evt);
            }
        });
        txt_G0iniX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G0iniXActionPerformed(evt);
            }
        });

        jLabel12.setText("Z");

        txt_G0iniZ.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G0iniZ.setToolTipText("Posicion de seguridad en Z");
        txt_G0iniZ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G0iniZFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G0iniZFocusLost(evt);
            }
        });
        txt_G0iniZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G0iniZActionPerformed(evt);
            }
        });

        ckb_Refrigerante.setText("Refrigerante On/Off");
        ckb_Refrigerante.setToolTipText("Seleccione para activar el refrigerante");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_G0iniZ, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_G0iniX, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckb_Refrigerante)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_G0iniX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_G0iniZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckb_Refrigerante))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel24.setText("[µm]");

        jLabel29.setText("Picoteo en Z:");

        txt_Q.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Q.setToolTipText("Longitud que se desplaza la herramienta en cada picoteo para lograr el ancho deseado de la ranura");
        txt_Q.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_QFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_QFocusLost(evt);
            }
        });
        txt_Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_QActionPerformed(evt);
            }
        });

        jLabel25.setText("[µm]");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel33.setText("Posicionamiento final:");

        jLabel2.setText("Modo:");

        cbx_PosFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambos a la vez", "Primero X luego Z", "Primero Z luego X" }));
        cbx_PosFinal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_PosFinalItemStateChanged(evt);
            }
        });

        jLabel34.setText("X");

        txt_G0Xf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G0Xf.setToolTipText("Posicion final en X");
        txt_G0Xf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G0XfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G0XfFocusLost(evt);
            }
        });
        txt_G0Xf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G0XfActionPerformed(evt);
            }
        });

        jLabel35.setText("Z");

        txt_G0Zf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G0Zf.setToolTipText("Posicion final en Z");
        txt_G0Zf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G0ZfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G0ZfFocusLost(evt);
            }
        });
        txt_G0Zf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G0ZfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_G0Xf, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_G0Zf, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx_PosFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbx_PosFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_G0Zf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_G0Xf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel36)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_F, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_X, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addGap(3, 3, 3)
                                .addComponent(txt_R, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_W, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_P, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Des, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addGap(1, 1, 1)
                .addComponent(txt_Des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(txt_X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txt_W, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txt_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel29)
                    .addComponent(txt_Q, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btn_Aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_XFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_XFocusGained
        txt_X.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_XFocusGained

    private void txt_XFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_XFocusLost
        txt_X.setBackground(Color.white);
    }//GEN-LAST:event_txt_XFocusLost

    private void txt_XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_XActionPerformed
        txt_X.transferFocus();
    }//GEN-LAST:event_txt_XActionPerformed

    private void txt_RFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RFocusGained
        txt_R.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_RFocusGained

    private void txt_RFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RFocusLost
        txt_R.setBackground(Color.white);
    }//GEN-LAST:event_txt_RFocusLost

    private void txt_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RActionPerformed
        txt_R.transferFocus();
    }//GEN-LAST:event_txt_RActionPerformed

    private void txt_FFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FFocusGained
        txt_F.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_FFocusGained

    private void txt_FFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FFocusLost
        txt_F.setBackground(Color.white);
    }//GEN-LAST:event_txt_FFocusLost

    private void txt_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FActionPerformed
        txt_F.transferFocus();
    }//GEN-LAST:event_txt_FActionPerformed

    private void txt_WFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_WFocusGained
        txt_W.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_WFocusGained

    private void txt_WFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_WFocusLost
        txt_W.setBackground(Color.white);
    }//GEN-LAST:event_txt_WFocusLost

    private void txt_WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_WActionPerformed
        txt_W.transferFocus();
    }//GEN-LAST:event_txt_WActionPerformed

    private void txt_PFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PFocusGained
        txt_P.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_PFocusGained

    private void txt_PFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PFocusLost
        txt_P.setBackground(Color.white);
    }//GEN-LAST:event_txt_PFocusLost

    private void txt_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PActionPerformed
        txt_P.transferFocus();
    }//GEN-LAST:event_txt_PActionPerformed

    private void txt_G0XfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0XfFocusGained
        txt_G0Xf.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G0XfFocusGained

    private void txt_G0XfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0XfFocusLost
        txt_G0Xf.setBackground(Color.white);
    }//GEN-LAST:event_txt_G0XfFocusLost

    private void txt_G0XfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G0XfActionPerformed
        txt_G0Xf.transferFocus();
    }//GEN-LAST:event_txt_G0XfActionPerformed

    private void txt_G0ZfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0ZfFocusGained
        txt_G0Zf.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G0ZfFocusGained

    private void txt_G0ZfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0ZfFocusLost
        txt_G0Zf.setBackground(Color.white);
    }//GEN-LAST:event_txt_G0ZfFocusLost

    private void txt_G0ZfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G0ZfActionPerformed
        txt_G0Zf.transferFocus();
    }//GEN-LAST:event_txt_G0ZfActionPerformed

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        if (rdb_G97.isSelected()) {
            if (!txt_G97S.getText().equals("")) {
                Velocidad = "G97 M3 S" + txt_G97S.getText() + ";" + '\n';
            } else {
                Velocidad = "";
            }
        } else {
            if (!txt_G96S.getText().equals("")) {
                Velocidad = "G96 M3 S" + txt_G96S.getText() + ";" + '\n';
            } else {
                Velocidad = "";
            }
        }
        PosIni = "G0 X" + txt_G0iniX.getText() + ";" + '\n';
        PosIni = PosIni + "Z" + txt_G0iniZ.getText();
        if (ckb_Refrigerante.isSelected()) {
            PosIni = PosIni + " M8;" + '\n';
        } else {
            PosIni = PosIni + ";" + '\n';
        }
        switch (modoFinal) {
            case 0:
                if (!txt_G0Xf.getText().equals("") && !txt_G0Zf.getText().equals("")) {
                    PosFin = "G0 X" + txt_G0Xf.getText() + " Z" + txt_G0Zf.getText();
                } else {
                    JOptionPane.showConfirmDialog(this, "Debe ingresar X final y Z final", "FALA POSICION FINAL", JOptionPane.CLOSED_OPTION);
                    return;
                }
                break;
            case 1:
                if (!txt_G0Xf.getText().equals("")) {
                    if (!txt_G0Zf.getText().equals("")) {
                        PosFin = "G0 X" + txt_G0Xf.getText() + ";" + '\n' + "Z" + txt_G0Zf.getText();
                    } else {
                        PosFin = "G0 X" + txt_G0Xf.getText();
                    }
                } else {
                    JOptionPane.showConfirmDialog(this, "Debe ingresar X final", "FALA POSICION FINAL", JOptionPane.CLOSED_OPTION);
                    return;
                }
                break;
            case 2:
                if (!txt_G0Zf.getText().equals("")) {
                    if (!txt_G0Xf.getText().equals("")) {
                        PosFin = "G0 Z" + txt_G0Zf.getText() + ";" + '\n' + "X" + txt_G0Xf.getText();
                    } else {
                        PosFin = "G0 Z" + txt_G0Zf.getText();
                    }
                } else {
                    JOptionPane.showConfirmDialog(this, "Debe ingresar Z final", "FALA POSICION FINAL", JOptionPane.CLOSED_OPTION);
                    return;
                }
                break;
        }
        if (ckb_Refrigerante.isSelected()) {
            PosFin = PosFin + " M9;" + '\n';
        } else {
            PosFin = PosFin + ";" + '\n';
        }
        if (!txt_Des.getText().equals("")) {
            Principal.Procesos = Principal.Procesos + "(" + txt_Des.getText() + ");" + '\n';
        }
        Principal.Procesos = Principal.Procesos + Velocidad;
        Principal.Procesos = Principal.Procesos + PosIni;
        Principal.Procesos = Principal.Procesos + "G75 R" + txt_R.getText() + ";" + '\n';
        Principal.Procesos = Principal.Procesos + "G75 X" + txt_X.getText() + " W" + txt_W.getText() + " P" + txt_P.getText() + " Q" + txt_Q.getText() + " F" + txt_F.getText() + ";" + '\n';
        Principal.Procesos = Principal.Procesos + PosFin;
        Inicial.Herr = true;
        this.dispose();
    }//GEN-LAST:event_btn_AceptarActionPerformed

    private void txt_DesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DesFocusGained
        txt_Des.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_DesFocusGained

    private void txt_DesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DesFocusLost
        txt_Des.setBackground(Color.white);
        txt_Des.setText(txt_Des.getText().toUpperCase());
    }//GEN-LAST:event_txt_DesFocusLost

    private void txt_DesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DesActionPerformed
        txt_Des.setText(txt_Des.getText().toUpperCase());
        txt_Des.transferFocus();
    }//GEN-LAST:event_txt_DesActionPerformed

    private void rdb_G50ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdb_G50ItemStateChanged
        if (!rdb_G50.isSelected()) {
            txt_G96S.setText("");
        }
        txt_G96S.setEnabled(rdb_G50.isSelected());
    }//GEN-LAST:event_rdb_G50ItemStateChanged

    private void rdb_G97ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdb_G97ItemStateChanged
        if (!rdb_G97.isSelected()) {
            txt_G97S.setText("");
        }
        txt_G97S.setEnabled(rdb_G97.isSelected());
    }//GEN-LAST:event_rdb_G97ItemStateChanged

    private void txt_G97SFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G97SFocusGained
        txt_G97S.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G97SFocusGained

    private void txt_G97SFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G97SFocusLost
        txt_G97S.setBackground(Color.white);
    }//GEN-LAST:event_txt_G97SFocusLost

    private void txt_G97SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G97SActionPerformed
        txt_G97S.transferFocus();
    }//GEN-LAST:event_txt_G97SActionPerformed

    private void txt_G96SFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G96SFocusGained
        txt_G96S.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G96SFocusGained

    private void txt_G96SFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G96SFocusLost
        txt_G96S.setBackground(Color.white);
    }//GEN-LAST:event_txt_G96SFocusLost

    private void txt_G96SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G96SActionPerformed
        txt_G96S.transferFocus();
    }//GEN-LAST:event_txt_G96SActionPerformed

    private void txt_G0iniXFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0iniXFocusGained
        txt_G0iniX.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G0iniXFocusGained

    private void txt_G0iniXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0iniXFocusLost
        txt_G0iniX.setBackground(Color.white);
    }//GEN-LAST:event_txt_G0iniXFocusLost

    private void txt_G0iniXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G0iniXActionPerformed
        txt_G0iniX.transferFocus();
    }//GEN-LAST:event_txt_G0iniXActionPerformed

    private void txt_G0iniZFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0iniZFocusGained
        txt_G0iniZ.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G0iniZFocusGained

    private void txt_G0iniZFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0iniZFocusLost
        txt_G0iniZ.setBackground(Color.white);
    }//GEN-LAST:event_txt_G0iniZFocusLost

    private void txt_G0iniZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G0iniZActionPerformed
        txt_G0iniZ.transferFocus();
    }//GEN-LAST:event_txt_G0iniZActionPerformed

    private void txt_QFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_QFocusGained
        txt_Q.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_QFocusGained

    private void txt_QFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_QFocusLost
        txt_Q.setBackground(Color.white);
    }//GEN-LAST:event_txt_QFocusLost

    private void txt_QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_QActionPerformed
        txt_Q.transferFocus();
    }//GEN-LAST:event_txt_QActionPerformed

    private void btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularActionPerformed
        new CalculoVelocidades(null, true).setVisible(true);
    }//GEN-LAST:event_btn_CalcularActionPerformed

    private void cbx_PosFinalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_PosFinalItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            modoFinal = cbx_PosFinal.getSelectedIndex();
        }
    }//GEN-LAST:event_cbx_PosFinalItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ranurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ranurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ranurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ranurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ranurado dialog = new Ranurado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_Calcular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbx_PosFinal;
    private javax.swing.JCheckBox ckb_Refrigerante;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rdb_G50;
    private javax.swing.JRadioButton rdb_G97;
    private javax.swing.JTextField txt_Des;
    private javax.swing.JTextField txt_F;
    private javax.swing.JTextField txt_G0Xf;
    private javax.swing.JTextField txt_G0Zf;
    private javax.swing.JTextField txt_G0iniX;
    private javax.swing.JTextField txt_G0iniZ;
    private javax.swing.JTextField txt_G96S;
    private javax.swing.JTextField txt_G97S;
    private javax.swing.JTextField txt_P;
    private javax.swing.JTextField txt_Q;
    private javax.swing.JTextField txt_R;
    private javax.swing.JTextField txt_W;
    private javax.swing.JTextField txt_X;
    // End of variables declaration//GEN-END:variables
}
