/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pqt;

import java.awt.Color;

/**
 *
 * @author PC
 */
public class Taladrado extends javax.swing.JDialog {

    String Velocidad = "";
    String PosIni = "";
    String PosFin = "";
    String Perfil = "";
    String PosFinAc = "";
    String PosIniAc = "";

    /**
     * Creates new form Taladrado
     * @param parent
     * @param modal
     */
    public Taladrado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        rdb_G50.setSelected(Principal.G50);
        rdb_G50.setEnabled(Principal.G50);
        rdb_G97.setSelected(!Principal.G50);
        txt_G96S.setEnabled(Principal.G50);
        this.setTitle("Taladrado frontal con picoteo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel36 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_Z = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_R = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_F = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_Q = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txt_G0Xf = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txt_G0Zf = new javax.swing.JTextField();
        btn_Aceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_Des = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rdb_G50 = new javax.swing.JRadioButton();
        rdb_G97 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_G97S = new javax.swing.JTextField();
        txt_G96S = new javax.swing.JTextField();
        btn_Calcular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_G0iniZ = new javax.swing.JTextField();
        ckb_Refrigerante = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel36.setText("Descripcion:");

        jLabel20.setText("Profundidad de perforado:");

        txt_Z.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Z.setToolTipText("Profundidad de la perforacion. Debe tener en cuenta la conicidad de la punta de la mecha");
        txt_Z.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_ZFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_ZFocusLost(evt);
            }
        });
        txt_Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ZActionPerformed(evt);
            }
        });

        jLabel22.setText("[mm]");

        jLabel21.setText("Retraccion:");

        txt_R.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_R.setToolTipText("Valor de retraccion de la herramienta luego de la pasada");
        txt_R.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_RFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_RFocusLost(evt);
            }
        });
        txt_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RActionPerformed(evt);
            }
        });

        jLabel23.setText("[mm]");

        jLabel28.setText("F");

        txt_F.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_F.setToolTipText("Velocidad de avance");
        txt_F.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_FFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_FFocusLost(evt);
            }
        });
        txt_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FActionPerformed(evt);
            }
        });

        jLabel1.setText("[mm/rev]");

        jLabel26.setText("Profundida de picoteo:");

        txt_Q.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Q.setToolTipText("Profundidad longitufinal del picoteo");
        txt_Q.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_QFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_QFocusLost(evt);
            }
        });
        txt_Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_QActionPerformed(evt);
            }
        });

        jLabel33.setText("Posicionamiento final:");

        jLabel34.setText("X");

        txt_G0Xf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G0Xf.setToolTipText("Posicion final en Z");
        txt_G0Xf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G0XfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G0XfFocusLost(evt);
            }
        });
        txt_G0Xf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G0XfActionPerformed(evt);
            }
        });

        jLabel35.setText("Z");

        txt_G0Zf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G0Zf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G0ZfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G0ZfFocusLost(evt);
            }
        });
        txt_G0Zf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G0ZfActionPerformed(evt);
            }
        });

        btn_Aceptar.setText("Aceptar");
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        txt_Des.setToolTipText("Nombre descriptivo del proceso");
        txt_Des.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_DesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_DesFocusLost(evt);
            }
        });
        txt_Des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DesActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(rdb_G50);
        rdb_G50.setText("Velocidad de corte constante (G96):");
        rdb_G50.setToolTipText("Seleccione para velocidad de corte constante");
        rdb_G50.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdb_G50ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rdb_G97);
        rdb_G97.setSelected(true);
        rdb_G97.setText("Velocidad de cabezal constante (G97):");
        rdb_G97.setToolTipText("Seleccione para velocidad de husillo constante");
        rdb_G97.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdb_G97ItemStateChanged(evt);
            }
        });

        jLabel5.setText("Velocidad de corte:");

        jLabel6.setText("[m/min]");

        jLabel7.setText("[RPM]");

        jLabel9.setText("Velocidad:");

        txt_G97S.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G97S.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G97SFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G97SFocusLost(evt);
            }
        });
        txt_G97S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G97SActionPerformed(evt);
            }
        });

        txt_G96S.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G96S.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G96SFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G96SFocusLost(evt);
            }
        });
        txt_G96S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G96SActionPerformed(evt);
            }
        });

        btn_Calcular.setText("Calcular");
        btn_Calcular.setFocusable(false);
        btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdb_G50)
                    .addComponent(rdb_G97)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_G97S, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Calcular))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_G96S, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdb_G50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txt_G96S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdb_G97)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(txt_G97S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Calcular))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Posicionamiento inicial:");

        jLabel12.setText("Z");

        txt_G0iniZ.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_G0iniZ.setToolTipText("Posicion de seguridad en Z");
        txt_G0iniZ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_G0iniZFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_G0iniZFocusLost(evt);
            }
        });
        txt_G0iniZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_G0iniZActionPerformed(evt);
            }
        });

        ckb_Refrigerante.setText("Refrigerante On/Off");
        ckb_Refrigerante.setToolTipText("Seleccione para activar el refrigerante");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_G0iniZ, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ckb_Refrigerante)
                        .addGap(14, 14, 14))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_G0iniZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckb_Refrigerante))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel24.setText("[µm]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel33)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel36)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Aceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_G0Xf, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel35)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_G0Zf, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_Des))))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_F, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(3, 3, 3)
                                .addComponent(txt_R, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Z, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addGap(1, 1, 1)
                .addComponent(txt_Des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22)
                    .addComponent(txt_Z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(txt_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txt_Q, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txt_F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_G0Xf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(txt_G0Zf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Aceptar)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ZFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ZFocusGained
        txt_Z.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_ZFocusGained

    private void txt_ZFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ZFocusLost
        String linea, arr[];
        arr = txt_Z.getText().split("-");
        if (arr.length == 1) {
            linea = "-" + txt_Z.getText();
            txt_Z.setText(linea);
        }
        txt_Z.setBackground(Color.white);
    }//GEN-LAST:event_txt_ZFocusLost

    private void txt_ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ZActionPerformed
        String linea, arr[];
        arr = txt_Z.getText().split("-");
        if (arr.length == 1) {
            linea = "-" + txt_Z.getText();
            txt_Z.setText(linea);
        }
        txt_Z.transferFocus();
    }//GEN-LAST:event_txt_ZActionPerformed

    private void txt_RFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RFocusGained
        txt_R.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_RFocusGained

    private void txt_RFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RFocusLost
        txt_R.setBackground(Color.white);
    }//GEN-LAST:event_txt_RFocusLost

    private void txt_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RActionPerformed
        txt_R.transferFocus();
    }//GEN-LAST:event_txt_RActionPerformed

    private void txt_FFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FFocusGained
        txt_F.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_FFocusGained

    private void txt_FFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FFocusLost
        txt_F.setBackground(Color.white);
    }//GEN-LAST:event_txt_FFocusLost

    private void txt_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FActionPerformed
        txt_F.transferFocus();
    }//GEN-LAST:event_txt_FActionPerformed

    private void txt_QFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_QFocusGained
        txt_Q.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_QFocusGained

    private void txt_QFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_QFocusLost
        txt_Q.setBackground(Color.white);
    }//GEN-LAST:event_txt_QFocusLost

    private void txt_QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_QActionPerformed
        txt_Q.transferFocus();
    }//GEN-LAST:event_txt_QActionPerformed

    private void txt_G0XfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0XfFocusGained
        txt_G0Xf.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G0XfFocusGained

    private void txt_G0XfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0XfFocusLost
        txt_G0Xf.setBackground(Color.white);
    }//GEN-LAST:event_txt_G0XfFocusLost

    private void txt_G0XfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G0XfActionPerformed
        txt_G0Xf.transferFocus();
    }//GEN-LAST:event_txt_G0XfActionPerformed

    private void txt_G0ZfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0ZfFocusGained
        txt_G0Zf.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G0ZfFocusGained

    private void txt_G0ZfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0ZfFocusLost
        txt_G0Zf.setBackground(Color.white);
    }//GEN-LAST:event_txt_G0ZfFocusLost

    private void txt_G0ZfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G0ZfActionPerformed
        txt_G0Zf.transferFocus();
    }//GEN-LAST:event_txt_G0ZfActionPerformed

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        if (rdb_G97.isSelected()) {
            if (!txt_G97S.getText().equals("")) {
                Velocidad = "G97 M3 S" + txt_G97S.getText() + ";" + '\n';
            } else {
                Velocidad = "";
            }
        } else {
            if (!txt_G96S.getText().equals("")) {
                Velocidad = "G96 M3 S" + txt_G96S.getText() + ";" + '\n';
            } else {
                Velocidad = "";
            }
        }
        PosIni = "G0 X0;" + '\n';
        PosIni = PosIni + "Z" + txt_G0iniZ.getText();
        PosFin = PosFin + "G0 Z" + txt_G0Zf.getText() + ";" + '\n';
        PosFin = PosFin + "X" + txt_G0Xf.getText();
        if (ckb_Refrigerante.isSelected()) {
            PosIni = PosIni + " M8;" + '\n';
            PosFin = PosFin + " M9;" + '\n';
        } else {
            PosIni = PosIni + ";" + '\n';
            PosFin = PosFin + ";" + '\n';
        }
        if (!txt_Des.getText().equals("")) {
            Principal.Procesos = Principal.Procesos + "(" + txt_Des.getText() + ");" + '\n';
        }
        Principal.Procesos = Principal.Procesos + Velocidad;
        Principal.Procesos = Principal.Procesos + PosIni;
        Principal.Procesos = Principal.Procesos + "G74 R" + txt_R.getText() + ";" + '\n';
        Principal.Procesos = Principal.Procesos + "G74 Z" + txt_Z.getText() + " Q" + txt_Q.getText() + " F" + txt_F.getText() + ";" + '\n';
        Principal.Procesos = Principal.Procesos + PosFin;
        Inicial.Herr = true;
        this.dispose();
    }//GEN-LAST:event_btn_AceptarActionPerformed

    private void txt_DesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DesFocusGained
        txt_Des.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_DesFocusGained

    private void txt_DesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DesFocusLost
        txt_Des.setBackground(Color.white);
        txt_Des.setText(txt_Des.getText().toUpperCase());
    }//GEN-LAST:event_txt_DesFocusLost

    private void txt_DesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DesActionPerformed
        txt_Des.setText(txt_Des.getText().toUpperCase());
        txt_Des.transferFocus();
    }//GEN-LAST:event_txt_DesActionPerformed

    private void rdb_G50ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdb_G50ItemStateChanged
        if (!rdb_G50.isSelected()) {
            txt_G96S.setText("");
        }
        txt_G96S.setEnabled(rdb_G50.isSelected());
    }//GEN-LAST:event_rdb_G50ItemStateChanged

    private void rdb_G97ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdb_G97ItemStateChanged
        if (!rdb_G97.isSelected()) {
            txt_G97S.setText("");
        }
        txt_G97S.setEnabled(rdb_G97.isSelected());
    }//GEN-LAST:event_rdb_G97ItemStateChanged

    private void txt_G97SFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G97SFocusGained
        txt_G97S.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G97SFocusGained

    private void txt_G97SFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G97SFocusLost
        txt_G97S.setBackground(Color.white);
    }//GEN-LAST:event_txt_G97SFocusLost

    private void txt_G97SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G97SActionPerformed
        txt_G97S.transferFocus();
    }//GEN-LAST:event_txt_G97SActionPerformed

    private void txt_G96SFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G96SFocusGained
        txt_G96S.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G96SFocusGained

    private void txt_G96SFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G96SFocusLost
        txt_G96S.setBackground(Color.white);
    }//GEN-LAST:event_txt_G96SFocusLost

    private void txt_G96SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G96SActionPerformed
        txt_G96S.transferFocus();
    }//GEN-LAST:event_txt_G96SActionPerformed

    private void txt_G0iniZFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0iniZFocusGained
        txt_G0iniZ.setBackground(Color.lightGray);
    }//GEN-LAST:event_txt_G0iniZFocusGained

    private void txt_G0iniZFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_G0iniZFocusLost
        txt_G0iniZ.setBackground(Color.white);
    }//GEN-LAST:event_txt_G0iniZFocusLost

    private void txt_G0iniZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_G0iniZActionPerformed
        txt_G0iniZ.transferFocus();
    }//GEN-LAST:event_txt_G0iniZActionPerformed

    private void btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularActionPerformed
        new CalculoVelocidades(null, true).setVisible(true);
    }//GEN-LAST:event_btn_CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Taladrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Taladrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Taladrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Taladrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Taladrado dialog = new Taladrado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_Calcular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ckb_Refrigerante;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rdb_G50;
    private javax.swing.JRadioButton rdb_G97;
    private javax.swing.JTextField txt_Des;
    private javax.swing.JTextField txt_F;
    private javax.swing.JTextField txt_G0Xf;
    private javax.swing.JTextField txt_G0Zf;
    private javax.swing.JTextField txt_G0iniZ;
    private javax.swing.JTextField txt_G96S;
    private javax.swing.JTextField txt_G97S;
    private javax.swing.JTextField txt_Q;
    private javax.swing.JTextField txt_R;
    private javax.swing.JTextField txt_Z;
    // End of variables declaration//GEN-END:variables
}
